  version: '2'

  services:
    web:
      build: .
      ports:
        - "8091:8080"
      networks:
        - my_network
      environment:
        POSTGRES: postgres
        POSTGRES_USERNAME: postgres
        POSTGRES_PASSWORD: mysecretword

    postgres:
      image: postgres
      networks:
        - my_network
      environment:
        POSTGRES_PASSWORD: mysecretword

  networks:
    my_network: